// Autogenerated for /opt/code/C/Kernel/repos/svit_kernel

// xt_family is declared in <linux/netfilter_ipv4/ip_tables.h>
#define HAVE_XT_FAMILY

#undef HAVE_TIMEVAL
// struct timeval is undeclared in <linux/ktime.h>. Compile:
//   #include <linux/module.h>
//   #include <linux/ktime.h>
//   MODULE_LICENSE("GPL");
//   struct timeval test;
// Output:
//   make -s -B -C /opt/code/C/Kernel/repos/svit_kernel M=/opt/code/C/Kernel/repos/Network/ipt-netflow/cc-test-build modules
//   /opt/code/C/Kernel/repos/Network/ipt-netflow/cc-test-build/test.c:4:16: error: storage size of 'test' isn't known
//       4 | struct timeval test;
//         |                ^~~~
//   make[2]: *** [scripts/Makefile.build:277: /opt/code/C/Kernel/repos/Network/ipt-netflow/cc-test-build/test.o] Error 1
//   make[1]: *** [Makefile:1884: /opt/code/C/Kernel/repos/Network/ipt-netflow/cc-test-build] Error 2

// struct proc_ops is declared in <linux/proc_fs.h>
#define HAVE_PROC_OPS

#undef HAVE_SYNCHRONIZE_SCHED
// synchronize_sched is undeclared in <linux/rcupdate.h>. Compile:
//   #include <linux/module.h>
//   #include <linux/rcupdate.h>
//   MODULE_LICENSE("GPL");
//   void *test = synchronize_sched;
// Output:
//   make -s -B -C /opt/code/C/Kernel/repos/svit_kernel M=/opt/code/C/Kernel/repos/Network/ipt-netflow/cc-test-build modules
//   /opt/code/C/Kernel/repos/Network/ipt-netflow/cc-test-build/test.c:4:14: error: 'synchronize_sched' undeclared here (not in a function); did you mean 'synchronize_srcu'?
//       4 | void *test = synchronize_sched;
//         |              ^~~~~~~~~~~~~~~~~
//         |              synchronize_srcu
//   make[2]: *** [scripts/Makefile.build:277: /opt/code/C/Kernel/repos/Network/ipt-netflow/cc-test-build/test.o] Error 1
//   make[1]: *** [Makefile:1884: /opt/code/C/Kernel/repos/Network/ipt-netflow/cc-test-build] Error 2

// nf_bridge_info_get is declared in <linux/netfilter_bridge.h>
#define HAVE_NF_BRIDGE_INFO_GET

// struct vlan_dev_priv is declared in <linux/if_vlan.h>
#define HAVE_VLAN_DEV_PRIV

// put_unaligned_be24 is declared in <asm/unaligned.h>
#define HAVE_PUT_UNALIGNED_BE24

// totalram_pages is declared in <linux/mm.h>
#define HAVE_TOTALRAM_PAGES

// totalram_pages is declared in <linux/mm.h>
#define HAVE_TOTALRAM_PAGES_REF

// struct nf_ct_event_notifier.ct_event is declared in <net/netfilter/nf_conntrack_ecache.h>
#define HAVE_NF_CT_EVENT_NOTIFIER_CT_EVENT

// End of compat_def.h
